### ISSUE TITLE
Not compatible with Skyrim SE 1.6.640

### ISSUE THREAD

**Issue by Vurmiraaz** [doodlum/skyrim-shadow-boost#2]
![image](https://user-images.githubusercontent.com/60999555/199731664-af7c6ead-c111-466a-abf1-69c5ad4d42dc.png)

**Comment by doodlum** [comment]
"Due to my real-life situation I cannot offer support for my mods in the near future. I can still accept PRs for my mods, and authors can release modifications of my mod which can have DP enabled, going 100% to them if they require my mod, otherwise something like a 70-30 split distributed to me and other listed authors, would be recommended although not required."
